

on:
  push:
    branches: 
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ AKIA4VS4XTVJZB4V65B6 }}
          aws-secret-access-key: ${{ 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 }}
          aws-region: US East (Ohio) us-east-2

      - name: Deploy to S3
        run: |
          aws s3 sync.s3:// ${{ foodsiteassignment }} --delete
           
          
